import { StyleSheet } from "react-native";
import normalize from "react-native-normalize";

export const styles = StyleSheet.create({
    header:{
        borderWidth:1,
        borderBottomLeftRadius:30,
        borderBottomRightRadius:30,
        backgroundColor:'#299BD7',
        height:normalize(150),
        borderColor:'#299BD7',
        flexDirection:'row',
        alignItems:'center',
        padding:normalize(20),
    },
    rounder:{
        borderWidth:1,
        borderColor:'#299BD7',
        width:normalize(80),
        height:normalize(80),
        backgroundColor:'#808080',
        borderRadius:40
    },
    rounder2:{
        borderWidth:1,
        borderColor:'#299BD7',
        width:normalize(80),
        height:normalize(80),
        backgroundColor:'#808080',
        borderRadius:40
    },
    topup:{
        borderWidth:1,
        backgroundColor:'#dfdfdf',
        borderColor:'#dfdfdf',
        height:normalize(30),
        width:normalize(100),
        borderRadius:30,
        alignItems:'center',
        justifyContent:'center'
    },
    body:{
        paddingTop:normalize(30),
        paddingLeft:normalize(20),
        paddingRight:normalize(20),
        paddingBottom:normalize(20),
        alignItems:'center'
    },
    utama:{
        width:normalize(100),
        height:normalize(150),
        alignItems:'center',
        justifyContent:'center',
        padding:normalize(5),
        borderRadius:10
    },
    textmid:{
        flexDirection:'row',
        paddingTop:normalize(20),
        paddingLeft:normalize(10),
        paddingRight:normalize(10),
        paddingBottom:normalize(0),
    },
    secondary:{
        width:normalize(80),
        height:normalize(120),
        alignItems:'center',
        justifyContent:'center',
        padding:normalize(5),
        borderRadius:10
    },
    dokter: {
        width:normalize(150),
        height:normalize(150),
        alignItems:'center',
        justifyContent:'center',
        padding:normalize(5),
        borderRadius:10
    },
    produk:{
        width:normalize(160),
        height:normalize(200),
        alignItems:'center',
        padding:normalize(5),
        borderRadius:10
    }
})